# Generated by Django 4.2.2 on 2023-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_product_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desc',
            new_name='desc0',
        ),
        migrations.AddField(
            model_name='blog',
            name='desc1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='desc2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
