# Generated by Django 4.2.2 on 2023-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_desc_blog_desc0_blog_desc1_blog_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
    ]
