# Generated by Django 4.2.2 on 2023-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnails',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
