# Generated by Django 4.2.2 on 2023-07-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_phone_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(max_length=100)),
            ],
        ),
    ]
